---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oci-cluster-autoscaler-extra
rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    resources:
    - "*"
    verbs:
    - get
    - list
    - watch
    - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oci-cluster-autoscaler-extra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oci-cluster-autoscaler-extra
subjects:
  - kind: ServiceAccount
    name: oci-cluster-autoscaler
    namespace: capi-system
