---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oci-cluster-autoscaler-extra
rules:
  - apiGroups:
    # - cluster.x-k8s.io
    - infrastructure.cluster.x-k8s.io
    resources:
    - "*"  # Include all resources in this API group to be safe
    verbs:
    - get
    - list
    - watch
    - update
  # - apiGroups:
  #   - storage.k8s.io
  #   resources:
  #   -  volumeattachments
  #   verbs:
  #   - get
  #   - list
  #   - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oci-cluster-autoscaler-extra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oci-cluster-autoscaler-extra
subjects:
  - kind: ServiceAccount
    name: oci-cluster-autoscaler
    namespace: capi-system
