---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oci-autoscaling-operator
  namespace: capi-system
data:
  # read configuration also from this secret (mainly capociCertificate and capociPassphrase)
  secretName: oci-autoscaling-operator

  # Variables to configure autoscaling
  # Minimum and maximum number of nodes used for autoscaling
  ociAutoscalingNodegroupMin: "${autoscaling_nodegroup_min}"
  ociAutoscalingNodegroupMax: "${autoscaling_nodegroup_max}"
  # VM Shape to use
  ociAutoscalingShape: ${autoscaling_shape}
  ociAutoscalingShapeConfigCPUs: "${autoscaling_shapeconfig_cpu}"
  ociAutoscalingShapeConfigMemory: "${autoscaling_shapeconfig_memory}"

  # OCI related variables
  ociCompartmentId: ${compartment}
  ociVcnId: ${vcn}
  ociApiserverLb: ${apiserver_lb}
  ociSubnetId: ${subnet}
  ociNSGId: ${nsg}
  ociImageId: ${image}
  controlPlaneEndpoint: ${control_plane_endpoint}

  # Variables to configure CAPOCI deployment
  # TODO: use instance principal
  capociTenancyId: ${tenancy}
  capociUserId: ${user}
  capociFingerprint: ${fingerprint}
  capociRegion: ${region}
  capociUseInstancePrincipal: "false"

