---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: OCICluster
metadata:
  name: ${cluster_name}
  namespace: openshift-machine-api
  labels:
    cluster.x-k8s.io/cluster-name: ${cluster_name}
  annotations:
    # Using managed-by annotation to skip all infrastructure management did not work
    # cluster.x-k8s.io/managed-by: "external"
    # So we crafted a custom annotation to skip apiserver loadbalancer reconcile:
    cluster.x-k8s.io/skip-apiserver-lb-management: "true"
spec:
  compartmentId: ${compartment}
  controlPlaneEndpoint:
    host: ${control_plane_endpoint}
    port: 6443
  networkSpec:
    apiServerLoadBalancer:
      loadBalancerId: ${apiserver_lb}
    skipNetworkManagement: true
    vcn:
      id: ${vcn}
      subnets:
      - id: ${subnet}
        name: private
        role: worker
      networkSecurityGroup:
        list:
        - id: ${nsg}
          name: cluster-compute-nsg
          role: worker
