---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ${cluster_name}
  namespace: ${namespace}
  annotations:
    cluster.x-k8s.io/managed-by: self
  labels:
    cluster.x-k8s.io/cluster-name: ${cluster_name}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.128.0.0/14
    serviceDomain: cluster.local
    services:
      cidrBlocks:
        - 172.30.0.0/16
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: OCICluster
    name: ${cluster_name}
    namespace: ${namespace}
