---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: OCIMachineTemplate
metadata:
  name: ${cluster_name}-autoscaling
  namespace: ${capi_namespace}
spec:
  template:
    spec:
      imageId: ${image}
      compartmentId: ${compartment}
      shape: "${autoscaling_shape}"
      shapeConfig:
        ocpus: "${autoscaling_shapeconfig_cpu}"
        memoryInGBs: "${autoscaling_shapeconfig_memory}"
      isPvEncryptionInTransitEnabled: false
