---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: ${oci_cluster_name}
  namespace: ${capi_namespace}
  annotations:
    capacity.cluster-autoscaler.kubernetes.io/cpu: "${autoscaling_shapeconfig_cpu}"
    capacity.cluster-autoscaler.kubernetes.io/memory: "${autoscaling_shapeconfig_memory}G"
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "${autoscaling_nodegroup_min}"
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "${autoscaling_nodegroup_max}"
spec:
  clusterName: ${cluster_name}
  selector:
    matchLabels:
  template:
    spec:
      clusterName: ${cluster_name}
      bootstrap:
        dataSecretName: ${cluster_name}-bootstrap
      infrastructureRef:
        name: ${cluster_name}-autoscaling
        namespace: ${capi_namespace}
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: OCIMachineTemplate
