---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: ${cluster_name}-autoscaling
  namespace: openshift-machine-api
  annotations:
    capacity.cluster-autoscaler.kubernetes.io/cpu: "6"
    capacity.cluster-autoscaler.kubernetes.io/memory: 16G
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "0"
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "5"
spec:
  clusterName: ${cluster_name}
  replicas: 0
  selector:
    matchLabels:
  template:
    spec:
      clusterName: ${cluster_name}
      bootstrap:
        dataSecretName: ${cluster_name}-bootstrap
      infrastructureRef:
        name: ${cluster_name}-autoscaling
        namespace: openshift-machine-api
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: OCIMachineTemplate
